# Generated by Django 5.1.2 on 2024-11-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_section_body_remove_section_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
