# Generated by Django 5.1.2 on 2024-11-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_card_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='link',
        ),
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='urlName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
